/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable no-console */

/**
 * A logger function that will only logs on development
 * @param object - The object to log
 * @param comment - Autogenerated with `lg` snippet
 */
export default function logger(comment: any, object?: unknown): void {
  //   const showLogger = process.env.NODE_ENV !== 'production';
  //   if (!showLogger) return;

  console.log(
    '%c ============== INFO LOG ============== \n',
    'color: #22D3EE',
    `${
      typeof window !== 'undefined' && `pathname: ${window?.location.pathname}`
    }\n`,
    `${comment}${object}`
  );
}
